project:
  type: website
  output-dir: .

website:
  title: "STA 9750 2024 Submission Material"
  description:
    Course Projects for STA 9750 at Baruch College
  site-url: "https://matata668.github.io/STA9750-2024-FALL/"
  navbar:
    background: primary
    search: false
    
format:
  html:
    theme: flatly
    toc: false
