```{r}
if(!require("tidyverse")) install.packages("tidyverse")

# Let's start with Fare Revenue
library(tidyverse)
if(!file.exists("2022_fare_revenue.xlsx")){
    # This should work _in theory_ but in practice it's still a bit finicky
    # If it doesn't work for you, download this file 'by hand' in your
    # browser and save it as "2022_fare_revenue.xlsx" in your project
    # directory.
    download.file("http://www.transit.dot.gov/sites/fta.dot.gov/files/2024-04/2022%20Fare%20Revenue.xlsx", 
                  destfile="2022_fare_revenue.xlsx", 
                  quiet=FALSE, 
                  method="wget")
}
FARES <- readxl::read_xlsx("2022_fare_revenue.xlsx") |>
    select(-`State/Parent NTD ID`, 
           -`Reporter Type`,
           -`Reporting Module`,
           -`TOS`,
           -`Passenger Paid Fares`,
           -`Organization Paid Fares`) |>
    filter(`Expense Type` == "Funds Earned During Period") |>
    select(-`Expense Type`) |>
    group_by(`NTD ID`,       # Sum over different `TOS` for the same `Mode`
             `Agency Name`,  # These are direct operated and sub-contracted 
             `Mode`) |>      # of the same transit modality
                             # Not a big effect in most munis (significant DO
                             # tends to get rid of sub-contractors), but we'll sum
                             # to unify different passenger experiences
    summarize(`Total Fares` = sum(`Total Fares`)) |>
    ungroup()

# Next, expenses
if(!file.exists("2022_expenses.csv")){
    # This should work _in theory_ but in practice it's still a bit finicky
    # If it doesn't work for you, download this file 'by hand' in your
    # browser and save it as "2022_expenses.csv" in your project
    # directory.
    download.file("https://data.transportation.gov/api/views/dkxx-zjd6/rows.csv?date=20231102&accessType=DOWNLOAD&bom=true&format=true", 
                  destfile="2022_expenses.csv", 
                  quiet=FALSE, 
                  method="wget")
}
EXPENSES <- readr::read_csv("2022_expenses.csv") |>
    select(`NTD ID`, 
           `Agency`,
           `Total`, 
           `Mode`) |>
    mutate(`NTD ID` = as.integer(`NTD ID`)) |>
    rename(Expenses = Total) |>
    group_by(`NTD ID`, `Mode`) |>
    summarize(Expenses = sum(Expenses)) |>
    ungroup()

FINANCIALS <- inner_join(FARES, EXPENSES, join_by(`NTD ID`, `Mode`))
# Monthly Transit Numbers
library(tidyverse)
if(!file.exists("ridership.xlsx")){
    # This should work _in theory_ but in practice it's still a bit finicky
    # If it doesn't work for you, download this file 'by hand' in your
    # browser and save it as "ridership.xlsx" in your project
    # directory.
    download.file("https://www.transit.dot.gov/sites/fta.dot.gov/files/2024-09/July%202024%20Complete%20Monthly%20Ridership%20%28with%20adjustments%20and%20estimates%29_240903.xlsx", 
                  destfile="ridership.xlsx", 
                  quiet=FALSE, 
                  method="wget")
}
TRIPS <- readxl::read_xlsx("ridership.xlsx", sheet="UPT") |>
            filter(`Mode/Type of Service Status` == "Active") |>
            select(-`Legacy NTD ID`, 
                   -`Reporter Type`, 
                   -`Mode/Type of Service Status`, 
                   -`UACE CD`, 
                   -`TOS`) |>
            pivot_longer(-c(`NTD ID`:`3 Mode`), 
                            names_to="month", 
                            values_to="UPT") |>
            drop_na() |>
            mutate(month=my(month)) # Parse _m_onth _y_ear date specs
MILES <- readxl::read_xlsx("ridership.xlsx", sheet="VRM") |>
            filter(`Mode/Type of Service Status` == "Active") |>
            select(-`Legacy NTD ID`, 
                   -`Reporter Type`, 
                   -`Mode/Type of Service Status`, 
                   -`UACE CD`, 
                   -`TOS`) |>
            pivot_longer(-c(`NTD ID`:`3 Mode`), 
                            names_to="month", 
                            values_to="VRM") |>
            drop_na() |>
            group_by(`NTD ID`, `Agency`, `UZA Name`, 
                     `Mode`, `3 Mode`, month) |>
            summarize(VRM = sum(VRM)) |>
            ungroup() |>
            mutate(month=my(month)) # Parse _m_onth _y_ear date specs

USAGE <- inner_join(TRIPS, MILES) |>
    mutate(`NTD ID` = as.integer(`NTD ID`))
if(!require("DT")) install.packages("DT")
library(DT)

sample_n(USAGE, 1000) |> 
    mutate(month=as.character(month)) |> 
    DT::datatable()

```
```{r}
#1. Rename a column: UZA Name to metro_area

USAGE <- USAGE |> 
  rename(metro_area = "UZA Name")

sample_n(USAGE, 1000) |> 
  mutate(month = as.character(month)) |> 
  DT::datatable()

```
```{r}
#Task2: REcording the Mode Column

USAGE <- USAGE |>
    mutate(Mode=case_when(
        Mode == "HR" ~ "Heavy Rail",
        Mode == "DR" ~ "Demand Response",
        Mode == "FB" ~ "Ferryboat",
        Mode == "MB" ~ "Motorbus",
        Mode == "SR" ~ "Streetcar Rail",
        Mode == "TB" ~ "Trolleybus",
        Mode == "VP" ~ "Vanpool",
        Mode == "CB" ~ "Commuter Bus",
        Mode == "RB" ~ "Bus Rapid Transit",
        Mode == "LR" ~ "Light Rail",
        Mode == "YR" ~ "Hybrid Rail",
        Mode == "MG" ~ "Monorail/Automated Guideway",
        Mode == "CR" ~ "Commuter Rail",
        Mode == "AR" ~ "Alaska Railroad",
        Mode == "TR" ~ "Aerial Tramway",
        Mode == "HR" ~ "Heavy Rail",
        Mode == "IP" ~ "Inclined Plane",
        Mode == "PB" ~ "Publico",
        Mode == "CC" ~ "Cable Car",
        TRUE ~ "Unknown"))
```
```{r}
library(DT)
sample_n(USAGE, 1000) |> 
    mutate(month=as.character(month)) |> 
    DT::datatable()
```
```{r}
library(DT)
library(dplyr)

USAGE_Drop <- USAGE |>
  select(-`NTD ID`, -`3 Mode`) |>
  rename( Passenger_Trips = UPT,
          Vehicle_Revenue_Mile = VRM)
sample_n(USAGE_Drop, 1000) |> 
    mutate(month=as.character(month)) |> 
    DT::datatable()
```
```{r}
#Task 3: 
#1. What transit agency had the most total VRM in our data set?

top_agency <- USAGE_Drop |>
  group_by(Agency) |>
  summarize(Total_VRM = sum(Vehicle_Revenue_Mile, na.rm = TRUE)) |>
  arrange(desc(Total_VRM)) |>
  slice(1)

print(top_agency)
```
```{r}
#2. What transit mode had the most total VRM in our data set?
top_mode <- USAGE_Drop |>
  group_by(Mode) |>
  summarize(Total_VRM = sum(Vehicle_Revenue_Mile, na.rm = TRUE)) |>
  arrange(desc(Total_VRM)) |>
  slice(1)

print(top_mode)
```
```{r}
#3. How many trips were taken on the NYC Subway (Heavy Rail) in May 2024?


total_nyc_trips <- USAGE_Drop |>

   filter(Agency == "MTA New York City Transit",
          month == "2024-05-01",
          Mode == "Heavy Rail") |>
   group_by(Agency, Mode) |>
   summarize(total_trips = sum(Passenger_Trips, na.rm = TRUE)) |>
   slice(1)
print(total_nyc_trips)
```


```{r}
#5. How much did NYC subway ridership fall between April 2019 and April 2020?
#I am still working on this one. My apologies.

ridership_2019 <- USAGE_Drop |>
  filter(Agency == "MTA New York City Transit",
         month == 2019-04-01)   |>
  summarize(total_ridership_2019 = sum(Passenger_Trips), na.rm = TRUE )

print(ridership_2019)


#ridership_2020 <- USAGE_Drop |>
  #filter(Agency == "MTA New York City Transit",
         #month  == 2019-04-01 )  |>
  #summarize(total_ridership_2020 = sum(Passenger_Trips), na.rm = TRUE )

#fall_in_ridership= 2020-2019
#fall_ridership <- ridership_2020$total_ridership_2020 - ridership_2019$total_ridership_2019

#print(fall_ridership)

```
```{r}
#Task4. intresting facts
#4.a
# which month has the most Motorbus usage in 2020

most_motorbus_usage_2020 <- USAGE_Drop |>
  filter(year(month) == 2020, 
         Mode == "Motorbus") |>
  
  group_by(month) |>
  
  summarize(total_motorbus_usage = sum(Passenger_Trips, na.rm = TRUE)) |>
  
  filter(total_motorbus_usage == max(total_motorbus_usage)) |>
  
  ungroup()

print(most_motorbus_usage_2020)


```  
```{r}
#4.b
#  Change in MTA user in Feb2020 and March2020 to observe the impact of COVID in the use of public transportation.

mta_nyc_covid_analysis <- USAGE_Drop |>

  filter(Agency == "MTA New York City Transit", 
         year(month) == 2020, 
         month(month) %in% c(2, 3)) |>
  
  group_by(month) |>
  
  summarize(total_passenger_trips = sum(Passenger_Trips, na.rm = TRUE)) |>
  
  ungroup()

print(mta_nyc_covid_analysis)


```

```{r}
#4.c
# which metro area has highest number of passenger trip 2021

metro_area_highest_passenger_trip_2021 <- USAGE_Drop |>
  filter(year(month) == 2021) |>
  
  group_by(metro_area) |>
  
  summarize(total_passenger_trips = sum(Passenger_Trips, na.rm = TRUE)) |>

  arrange(desc(total_passenger_trips)) |>
  
  slice(1) |>
  
  ungroup()

print(metro_area_highest_passenger_trip_2021)


```

```{r}
#Task 5

USAGE_2022_ANNUAL <- USAGE |>
  filter(year(month) == 2022) |>
  group_by(`NTD ID`, Agency, metro_area, Mode) |>
  summarize(
    UPT = sum(UPT, na.rm = TRUE),  # Total UPT for each group
    VRM = sum(VRM, na.rm = TRUE)  # Total VRM for each group
  ) |>
  ungroup()
print(USAGE_2022_ANNUAL)
view(USAGE_2022_ANNUAL)

```

```{r}
FINANCIALS |>
  DT::datatable(options = list(pageLength = 10))
```
``` {r}
FINANCIALS <- FINANCIALS |>
   mutate(Mode=case_when(
        Mode == "HR" ~ "Heavy Rail",
        Mode == "DR" ~ "Demand Response",
        Mode == "FB" ~ "Ferryboat",
        Mode == "MB" ~ "Motorbus",
        Mode == "SR" ~ "Streetcar Rail",
        Mode == "TB" ~ "Trolleybus",
        Mode == "VP" ~ "Vanpool",
        Mode == "CB" ~ "Commuter Bus",
        Mode == "RB" ~ "Bus Rapid Transit",
        Mode == "LR" ~ "Light Rail",
        Mode == "YR" ~ "Hybrid Rail",
        Mode == "MG" ~ "Monorail/Automated Guideway",
        Mode == "CR" ~ "Commuter Rail",
        Mode == "AR" ~ "Alaska Railroad",
        Mode == "TR" ~ "Aerial Tramway",
        Mode == "HR" ~ "Heavy Rail",
        Mode == "IP" ~ "Inclined Plane",
        Mode == "PB" ~ "Publico",
        Mode == "CC" ~ "Cable Car",
        TRUE ~ "Unknown"))
  
```

```{r}
USAGE_AND_FINANCIALS <- left_join(
  USAGE_2022_ANNUAL,
  FINANCIALS,
  join_by(`NTD ID`, Mode)) |>
  drop_na()
view(USAGE_AND_FINANCIALS)
```


```{r}
#Task6.1

Most_UPT<- USAGE_AND_FINANCIALS |>
  group_by(Agency, Mode) |>
  summarize(
    total_UPT = sum(UPT, na.rm = TRUE)
  ) |>
  arrange(desc(total_UPT)) |>
  
  ungroup() |>

filter(total_UPT == max(total_UPT))

print(Most_UPT)

```

```{r}
#Task 6.2
highest_farebox_recovery <- USAGE_AND_FINANCIALS |>
  mutate(farebox_recovery = `Total Fares` / Expenses) |>
  
  filter(!is.na(Expenses) & Expenses > 0) |>
 
  arrange(desc(farebox_recovery)) |>

  filter(farebox_recovery == max(farebox_recovery))

print(highest_farebox_recovery)
view(highest_farebox_recovery)

```


```{r}
#Task6.3

lowest_expenses_per_upt <- USAGE_AND_FINANCIALS |>

  mutate(expenses_per_upt = Expenses / UPT) |>
  
  filter(!is.na(UPT) & UPT > 0) |>
  
  filter(expenses_per_upt == min(expenses_per_upt, na.rm = TRUE)) |>
  
  ungroup()

print(lowest_expenses_per_upt)
view(lowest_expenses_per_upt)

```

```{r} 
#Task6.4

highest_fares_per_upt <- USAGE_AND_FINANCIALS |>

  mutate(fares_per_upt = `Total Fares` / UPT) |>
  
  filter(!is.na(UPT) & UPT > 0) |>
  
  filter(fares_per_upt == max(fares_per_upt, na.rm = TRUE)) |>

  ungroup()

print(highest_fares_per_upt)

view(highest_fares_per_upt)

```

```{r}

#Task6.5
lowest_expenses_per_vrm <- USAGE_AND_FINANCIALS |>

  mutate(expenses_per_vrm = Expenses / VRM) |>
  

  filter(!is.na(VRM) & VRM > 0) |>
  

  filter(expenses_per_vrm == min(expenses_per_vrm, na.rm = TRUE)) |>
  

  ungroup()


print(lowest_expenses_per_vrm)
view(lowest_expenses_per_vrm)


```

```{r}
#Task 6.6
highest_fares_per_vrm <- USAGE_AND_FINANCIALS |>

  mutate(fares_per_vrm = `Total Fares` / VRM) |>
  
  filter(!is.na(VRM) & VRM > 0) |>
  
  filter(fares_per_vrm == max(fares_per_vrm, na.rm = TRUE)) |>
  
  ungroup()

print(highest_fares_per_vrm)
view(highest_fares_per_vrm)

```